[devshell]
name = "say-hello-to-satysfi"
packages = [
  "cargo-make",
  "alejandra",
  "dprint",
  "satysfi",
  "satysfi-formatter",
  "satysfi-language-server",
]

[[commands]]
package = "treefmt"
category = "formatter"
